# .gitlab-ci.yml
#

stages:
  - test
  - build


image:                             parity/rust:nightly

variables:
  CI_SERVER_NAME:                  "GitLab CI"
  CARGO_HOME:                      "${CI_PROJECT_DIR}/.cargo"

cache:
  key:                             "${CI_JOB_NAME}"
  paths:
    - ./.cargo/


#### stage:                        test

test:cmd:
  stage: test
  image: debian:buster-slim
  script:
    - cat /proc/cpuinfo
  tags:
    - linux-docker

test:rust:stable:
  stage:                           test
  script:
    - time cargo test --all
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust


#### stage:                        build

build:linux:ubuntu:amd64:
  stage:                           build
  script:
    - cargo build
  only:
    - master
    - tags
    - web
  tags:
    - rust

