# .gitlab-ci.yml
#

stages:
  - test
  - build

variables:
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       "100"
  CARGO_HOME:                      "/ci-cache/${CI_PROJECT_NAME}/cargo/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
  CARGO_TARGET_DIR:                "/ci-cache/${CI_PROJECT_NAME}/targets/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
  CARGO_INCREMENTAL:               0
  CI_SERVER_NAME:                  "GitLab CI"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.docker-env:                       &docker-env
  image:                           paritytech/ink-ci-linux:latest
  before_script:
    - cargo -vV
    - rustc -vV
    - rustup show
    - bash --version
    - ./scripts/pre_cache.sh
    - sccache -s
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME == "tags"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
  interruptible:                   true
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  tags:
    - linux-docker

#### stage:                        test

test-rust-stable:
  stage:                           test
  <<:                              *docker-env
  script:
    - time cargo test --verbose --all --features bit-vec,generic-array,derive
    - sccache -s

test-rust-stable-no_derive:
  stage:                           test
  <<:                              *docker-env
  script:
    - time cargo test --verbose --features bit-vec,generic-array
    - sccache -s

check-rust-stable-no_derive_no_std_full:
  stage:                           test
  <<:                              *docker-env
  script:
    - time cargo check --verbose --no-default-features --features bit-vec,generic-array,full
    - sccache -s

check-rust-stable-no_derive_no_std:
  stage:                           test
  <<:                              *docker-env
  script:
    - time cargo check --verbose --no-default-features --features bit-vec,generic-array
    - sccache -s

check-rust-stable-no_derive_full:
  stage:                           test
  <<:                              *docker-env
  script:
    - time cargo check --verbose --features bit-vec,generic-array,full
    - sccache -s

bench-rust-nightly:
  stage:                           test
  <<:                              *docker-env
  script:
    - time cargo +nightly bench --features bit-vec,generic-array,derive
    - sccache -s

#### stage:                        build

build-linux-ubuntu-amd64:
  stage:                           build
  <<:                              *docker-env
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME == "tags"
  script:
    - cargo build --verbose --release --features bit-vec,generic-array,derive
    - sccache -s
