# .gitlab-ci.yml
#

stages:
  - test
  - build


image:                             parity/rust:nightly

variables:
  CI_SERVER_NAME:                  "GitLab CI"
  CARGO_HOME:                      "${CI_PROJECT_DIR}/.cargo"

cache:
  key:                             "${CI_JOB_NAME}"
  paths:
    - ./.cargo/


#### stage:                        test

test:rust:stable:derive:
  stage:                           test
  script:
    - time cargo test --verbose --all --features bit-vec,derive
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

test:rust:stable:no_derive:
  stage:                           test
  script:
    - time cargo test --verbose --features bit-vec
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

bench:rust:nightly:
  stage:                           test
  script:
    - time cargo +nightly bench --features bit-vec,derive
  only:
    - triggers
    - tags
    - master
    - schedules
    - web
    - /^[0-9]+$/
  tags:
    - rust

#### stage:                        build

build:linux:ubuntu:amd64:
  stage:                           build
  script:
    - cargo build --verbose --release --features bit-vec,derive
  only:
    - master
    - tags
    - web
  tags:
    - rust

