[package]
name = "parity-codec"
description = "Lightweight, efficient, binary serialization and deserialization codec"
version = "1.1.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"

[dependencies]
arrayvec = { version = "0.4", default_features = false }

[features]
default = ["std"]
std = []

[workspace]
members = [
	"derive"
]