[package]
name = "parity-codec-derive"
description = "Serialization and deserialization derive macro for Parity Codec"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.26", features = [ "full", "visit" ] }
quote = "0.6"
proc-macro2 = "0.4"
proc-macro-crate = "0.1.3"

[features]
default = ["std"]
std = []
